# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 20:09
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(error_messages={'unique': 'Użytkownik o tym adresie już istnieje'}, max_length=254, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_password_change', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='data ostatniej zmiany hasła')),
                ('group', models.ForeignKey(blank=True, help_text='Grupa do której należy użytkownik.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='grupa')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='hasło')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_set', to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
        ),
    ]
