# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzone'),
        ),
        migrations.AlterField(
            model_name='book',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzone'),
        ),
        migrations.AlterField(
            model_name='lendinghistory',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='utworzone'),
        ),
    ]
