# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20171028_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, to='books.Tag', verbose_name='tagi'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='last_change',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='books.LendingHistory', verbose_name='ostatnia zmiana'),
        ),
        migrations.AlterField(
            model_name='lendinghistory',
            name='lending',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='books.Lending', verbose_name='wypożyczenie'),
        ),
    ]
